version: '3.9'
services:
   db:
      container_name: db
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=test
      ports:
         - 5432:5432
      volumes:
         - "postgres:/data/db"
volumes:
  postgres: 